### ISSUE TITLE
 logon_hours_ok: failed to get gmtime. Failing logon for user timemachine

### ISSUE THREAD

**Issue by brantonb** [awlx/samba-timemachine#9]
I'm running this Docker image on a Raspberry Pi 4. When I try to configure Time Machine, I get prompted for the username and password. When I enter the correct credentials, I get an error dialog:

>**Access to your account on the server "Time Capsule on <hostname>" has been denied.**
>Contact your system administrator for more information.
>[OK]

The Docker logs show this error message each time I attempt to connect:

```
 logon_hours_ok: failed to get gmtime. Failing logon for user timemachine
```

Here is how I created my container:

```sh
$ docker run -d \
    --name timemachine \
    -v timemachine_data:/backups \
    -p 10445:445 \
    -e SHARENAME=TimeMachine \
    -e USER=timemachine \
    -e PASS=<MY PASSWORD> \
    -e TMSIZE=500000 \
    --restart=unless-stopped \
    awlnx/samba-timemachine:latest
```

I'm guessing it's related to it being an arm processor.

**Comment by awlx** [comment]
Hm, that's weird that shouldn't have something to do with running on a raspberry.

**Comment by awlx** [comment]
@brantonb can you try again there was a samba upgrade, which I just published.

**Comment by brantonb** [comment]
Thanks for the quick response! Details below, but tl;dr: `alpine:latest` has time issues and `alpine:3.12` works.

Unfortunately, the new image doesn't seem to fix it. I deleted the container, ran `docker pull awlnx/samba-timemachine:latest`, and recreated the container with the same command as above.

```sh
$ docker container ls | grep timemachine
42fd6e9f29f6   awlnx/samba-timemachine:latest   "/entrypoint"            6 minutes ago   Up 6 minutes           0.0.0.0:10445->445/tcp, :::10445->445/tcp  

$ docker image ls | grep timemachine
awlnx/samba-timemachine   latest       c853556909da   6 hours ago   31.3MB
awlnx/samba-timemachine   <none>       453ddc50767e   4 days ago    31.3MB

$ docker container logs timemachine
Created group timemachine_users with 1311
Creating user timemachine with a samba password of <MY PASSWORD>
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
Added user timemachine.
Granting permissions to timemachine/1311 with  timemachine_users/1311 on /backups
smbd version 4.14.5 started.
Copyright Andrew Tridgell and the Samba Team 1992-2021
INFO: Profiling support unavailable in this build.
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
logon_hours_ok: failed to get gmtime. Failing logon for user timemachine
logon_hours_ok: failed to get gmtime. Failing logon for user timemachine
```

I found [the samba code that appears to be returning this](https://github.com/samba-team/samba/blob/master/source3/auth/check_samsec.c#L119):

```c
	lasttime = time(NULL);
	utctime = gmtime(&lasttime);
	if (!utctime) {
		DEBUG(1, ("logon_hours_ok: failed to get gmtime. Failing logon for user %s\n",
			pdb_get_username(sampass) ));
		return False;
	}
```

Which made me wonder what the time is in the container:

```sh
$ # Time on my Raspberry Pi
$ date
Thu 19 Aug 2021 08:01:38 AM PDT

$ # Time in the timemachine container
$ docker exec -it timemachine date
Mon Jun  8 08:34:56 UTC 2071

$ # Time in another container
$ docker exec -it another-container date
Thu Aug 19 15:05:24 UTC 2021
```

So I'm guessing it's related to the fact that the time is set to the year 2071. I found at least [one other issue](https://github.com/haugene/docker-transmission-openvpn/issues/1702) that was Raspberry Pi specific where the date was 2071. And there's [this Stack Overflow answer](https://stackoverflow.com/a/66179722) that discusses versions of Alpine that are affected. I eventually got to [this release note for Alpine 3.13](https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements) that talks about time64 requirements on 32 bit images.

I confirmed that if I change `FROM  alpine:latest` to `FROM alpine:3.12` that this issue is resolved. That's probably not the right fix, but it has me up and running.

**Comment by brantonb** [comment]
I ran across similar issues with other Docker images. This is a common issue for 32-bit Rasberry Pi OS images that was introduced with Alpine 3.13. The workaround is to install a patched version of `libseccomp2`, as documented here: https://docs.linuxserver.io/faq#libseccomp. I've confirmed that once I've done this, I can use `awlnx/samba-timemachine` without any issues. Closing this out.
